// Generated by https://quicktype.io

export interface HasSprintResponse {
  message: string;
  sprint: Sprint;
}

export interface Sprint {
    id:         number | null;
    sprint:     string | null;
    created_at: string | null;
}
